### PR TITLE
Add first-pass Numba versions

### PR DESCRIPTION
**Pull request by gforsyth**
Hey @serge-sans-paille -- thanks for putting this together!  
I haven't played much with Pythran but it works really well, sort of a battle back and forth for best performance between the three contenders.

I added first-pass Numba versions to all but the `max len seq inner` because Numba doesn't seem to support `numpy.roll` yet, and also Cython crashed on me once when I was running it.  Worth further investigation but my battery is dying and I'm without a charger.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
It might be worth emulating `np.roll` with slicing and `np.concatenate`.

**Comment by hameerabbasi** [comment]
Or maybe advanced indexing. I'm not entirely sure which will be faster.

**Comment by serge-sans-paille** [comment]
I thought there was a mixed mode in numba's jit, you could use it for np.roll, just as cython does, right?

**Comment by serge-sans-paille** [comment]
oh, and obviously, thanks for contributing to the effort, let's make all the compilers better :-)

**Comment by hameerabbasi** [comment]
> I thought there was a mixed mode in numba's jit, you could use it for np.roll, just as cython does, right?

As long as it's outside any tight loops, that should work just fine.

**Comment by gforsyth** [comment]
> I thought there was a mixed mode in numba's jit, you could use it for np.roll, just as cython does, right?

Yes.  I used that in one of the other notebooks to show the `numba` version with and without exception raising (which doesn't work in `nopython` mode).  

Even with a plain `jit` the `np.roll` kept crashing my kernel (also crashed once when i was running the Cython version).  Definitely needs further investigation there, but yes, in principle it should work.

**Comment by serge-sans-paille** [comment]
Thanks!

**Comment by serge-sans-paille** [comment]
btw, @gforsyth | @hameerabbasi do you know what kind of optimizations are enabled by numba's jit, anything specific to the target (namely, is vectorization using AVX if available on by default?). I assume we don't have fast-math, right?

**Comment by hameerabbasi** [comment]
I believe Numba currently does some SIMD instructions, not sure which. It uses LLVM with native CPU arch compilation, so any features supported by the LLVM version in llvmlite should already be there. Intel has also dedicated two-full time devs to Numba, so we can expect this to improve in the future.

**Comment by serge-sans-paille** [comment]
from my experience in llvm and what I can read in https://github.com/numba/numba/blob/f77b19adf31562b65b7886aab3b688ce1ff0d735/numba/targets/codegen.py and https://github.com/numba/numba/blob/58f6a2844da291d02dbb6169afd7e96dca8e07e7/numba/config.py they are using the equivalent of clang -O3 with vectorizer on.

**Comment by serge-sans-paille** [comment]
I'll update the notebooks to activate that with pythran and cython too.

**Comment by hameerabbasi** [comment]
It won't be a fair comparison because Pythran and Cython aren't JIT-compiled, so their code needs to be portable (if using wheels or similar). Numba, on the other hand, can tailor its code to any CPU.

**Comment by serge-sans-paille** [comment]
Well, that really depends: is the code compiled on the user laptop or distributed as a wheel? as a wheel it needs to be portable. When recompiled on the user machine, it can use the machine capability.

The best is probably to emphazise the difference (which is a real strong point for numba !) by running two sets of tests, one with portability in mind, and one with performance in mind ?

**Pull request merged**
